require_relative '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/.bun/@capacitor+ios@8.3.0+db0c1b46371b240c/node_modules/@capacitor/ios'
  pod 'CapacitorPreferences', :path => '../../../../node_modules/.bun/@capacitor+preferences@8.0.1+db0c1b46371b240c/node_modules/@capacitor/preferences'
  pod 'CapacitorSplashScreen', :path => '../../../../node_modules/.bun/@capacitor+splash-screen@8.0.1+db0c1b46371b240c/node_modules/@capacitor/splash-screen'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
